---
title: "Template for XRF Chemistry data Parsing"
output: html_notebook
---

# Over view

This is a data base for XRF chemistry Data set.

# Data sets

## Elements

```{r include=FALSE}
elements <-
  c("Al", "Si", "S", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "As", "Ag", "Sn", "Sb", "Au", "Pb", "Bi")
```

`r elements`

## Data set

```{r include=FALSE}
library(tidyverse)
library(magrittr)
library(readr)
library(janitor)

data_set <- read_csv("data.csv")

```
`r data_set`

## Clean Data set

```{r Cleaning data, echo=FALSE}
data_set_clean <- 
  data_set %>% select(!contains("Error")) %>%  # Removes the Errors
  select(id = Lab_ID, starts_with(elements)) %>% # Removes all Other elements
  select(!`Collimation Status`) %>% 
  select(id, sort(names(.)))

data_set_clean
```


## List of Mean and Standard Diviation

```{r echo=FALSE}
data_overview <- 
  data_set_clean %>%
  group_by(id) %>% 
  summarise(across(everything(), list(mean = mean, sd = sd)))

data_overview
```

```{r}

library(viridis)

data_mean <- data_overview %>% pivot_longer(cols = (contains("mean")), names_to = "Type", values_to = "Value_mean") %>%  select(id, Type, Value_mean)

data_sd <- data_overview %>% pivot_longer(cols = (contains("sd")), names_to = "Type", values_to = "Value_sd") %>% select(id, Type, Value_sd)

data_mean$Type <- data_mean$Type %>% substr(1,2)
data_sd$Type <- data_sd$Type %>% substr(1,2)

data_join <- full_join(data_mean, data_sd, by = join_by(id, Type))

ggplot(data_join) +
  geom_bar(aes(x=id, y=Value_mean, fill = Type), stat = "identity", position="identity") +
  geom_errorbar(aes(x = id, ymin = Value_mean-Value_sd, ymax = Value_mean+Value_sd,
                    fill = Type),  position="identity")+
  scale_fill_viridis(discrete=TRUE, name="")
```


# Isolated Items which conatin a high Standar Diviation

```{r echo=FALSE}
high_sd <- 
  function(x){
  x >= 3
  }

data_isolated <-
  data_overview %>% 
  filter(if_any(ends_with("sd"), high_sd)) %>% 
  select(id, ends_with("sd")) %>% 
  select_if(~ any(high_sd(.)))

data_isolated
```

Items which are Isolated `r data_isolated$id %>% as.array()`

## Data set of Isloated Items

```{r echo=FALSE}

columns <-
  substr(colnames(data_isolated[2:(max(col(data_isolated)))]),
         start = 1,
         stop = 2)

data_set_isolated <- data_set_clean %>% 
  filter(id %in% (data_isolated$id %>% as.array())) %>% 
  arrange(id) %>% 
  group_by(id) %>% 
  select(id, starts_with(columns)) %>% 
  mutate(across(everything(), list(z_score = scale))) %>% 
  select(id, sort(names(.)))# %>% 
  #select_if(~ any(. > 4))
  #filter(if_any(ends_with("Concentration"), outliers))

data_set_isolated
```
